spring:
  profiles:
    active: local
  sql:
    init:
      mode: always
      platform: local

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:~/morak-dev;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true

---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:~/morak-dev;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true

security:
  jwt:
    token:
      secret-key: “eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno”
      expire-length: 3600000
  oauth:
    github:
      client-id: ${GITHUB_CLIENT_ID}
      client-secret: ${GITHUB_CLIENT_SECRET}
