# Global Configuration

spring:
  profiles:
    active: local, schedule
  jpa:
    properties:
      hibernate:
        batch_fetch_style: padded
        default_batch_fetch_size: 100
        connection:
          provider_disables_autocommit: true
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    log-resolved-exception: off
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    hikari:
      maximum-pool-size: 5
      connection-timeout: 3000
      auto-commit: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  tomcat:
    accept-count: 200
    max-connections: 400
    threads:
      max: 10
  shutdown: graceful

logging:
  slack:
    error-url: ${SLACK_ERROR_URL}
  config: classpath:logback-spring.xml

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-length: ${EXPIRED_TIME}
  oauth:
    github:
      client-id: ${GITHUB_CLIENT_ID}
      client-secret: ${GITHUB_CLIENT_SECRET}
  slack:
    notification:
      slack:
        url: ${SLACK_ERROR_URL}

---

# Production Configuration

spring:
  config:
    activate:
      on-profile: prd
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:3306/${DATABASE_NAME}?serverTimezone=Asia/Seoul&character_set_server=utf8mb4
    username: ${USERNAME}
    password: ${PASSWORD}
  application:
    name: morak-prd
  sql:
    init:
      mode: never
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
cors:
  allowed-origin: ${ALLOWED_ORIGIN}
monitoring:
  prometheus:
    origin: ${PROMETHEUS_ORIGIN}

---

# Development Configuration

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:3306/${DATABASE_NAME}?serverTimezone=Asia/Seoul&character_set_server=utf8mb4
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  application:
    name: morak-dev
  sql:
    init:
      mode: always
      platform: dev
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
cors:
  allowed-origin: ${ALLOWED_ORIGIN}
monitoring:
  prometheus:
    origin: ${PROMETHEUS_ORIGIN}
---

# Local Configuration

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:33306/morak?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      platform: local
  application:
    name: morak-local

logging:
  level:
    org:
      springframework:
        transaction.interceptor: TRACE
cors:
  allowed-origin: "*"
monitoring:
  prometheus:
    origin: localhost

